# apiVersion: v1
# kind: Secret

# metadata:
#   name: app-secret

# type: Opaque

# stringData:
#   JWT_SECRET: myjwtsecret
#   MONGO_URI: mongodb://mongo:27017/linkedin
apiVersion: v1
kind: Secret

metadata:
  name: app-secret

type: Opaque

stringData:
  JWT_SECRET: jay@123
  MONGODB_URI: "mongodb+srv://vikashtiwari9893_db_user:MhreUqiAZ9HsxeGp@cluster0.qocsfdy.mongodb.net/?appName=Cluster0"